## 넘파이 NumPy ndarray: 다차원 배열 객체

#### Numerical Python의 줄임말

1. 빠르고 효율적인 메모리 사용, 벡터 연산, 브로드캐스팅(확대) 기능을 제공하는 다차원 배열인 ndarray (n dimentional array)를 제공
1. for 문 등 반복문을 작성할 필요없이 전체 배열에 대해 빠른 연산을 제공
1. 배열 데이터를 디스크에 쓰거나 읽을 수 있는 도구
1. 선형대수, 난수 발생기, 푸리에(Fourier) 변환 기능
1. C, C++, 포트란 등 다른 언어로 쓰여진 코드를 통합하는 도구

## 1.넘파이 자료형 ndarray : 다차원 배열 객체 

#####  NumPy의 핵심 기능 중 하나는 ndarray라고 하는 n차원의 배열 객체. 파이썬에서 사용할 수 있는 대규모 데이터 집합을 담을 수 있는 있는 빠르고 유용한 구조

In [12]:
# np.array(object, dtype) object는 ndarray로 변환할 배열이며, dtype은 ndarray 요소의 자료형

In [7]:
import numpy as np
L = [1, 2, 3]  
arr = np.array(L) 
arr       

array([1, 2, 3])

In [6]:
arr * 3

array([3, 6, 9])

In [7]:
arr + arr

array([2, 4, 6])

#### 참고. 파이썬 리스트와 비교 

In [13]:
L * 3 

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [11]:
L + L 

[1, 2, 3, 1, 2, 3]

### ndarray : 다차원 배열 객체 


In [11]:
##numpy 패키지를 임포트하여 임의의 값이 들어 있는 배열 생성 

import numpy as np 

data = np.random.randn(2, 3)

data


array([[ 0.92232193, -1.42785941,  1.90692312],
       [ 0.74244544,  0.16978314, -0.37038063]])

In [13]:
data * 10 


array([[ 1.84464385, -2.85571883,  3.81384625],
       [ 1.48489088,  0.33956627, -0.74076126]])

In [14]:
data + data

array([[ 1.84464385, -2.85571883,  3.81384625],
       [ 1.48489088,  0.33956627, -0.74076126]])

In [15]:
data.shape

(2, 3)

### ndarray 생성하기

In [19]:
# array 함수를 이용하면 손쉽게 배열을 생성할 수 있다. 순차적인 객체를 넘겨받고, 넘겨받은 데이터가 들어 있는 새로운 NumPy 배열을 생성
# array 함수는 리스트와 튜플 등을 ndarray 형태로 바꿈 
# 파이썬 list를 array로 변경하기

data1 = [5, 6.5, 7, 9, 10]   #1차원 벡터 
arr1 = np.array(data1)

arr1 

array([ 5. ,  6.5,  7. ,  9. , 10. ])

In [24]:
# 같은 길이를 가지는 리스트를 내포하고 있는 데이터는 다차원 배열로 전환 가능

data2 = [[1, 2, 3, 4],[5, 6, 7, 8]] #2차원 행렬

arr2 = np.array(data2)

arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
# ndim과 shape 속성을 활용해서 차원을 확인할 수 있음

arr2.ndim


2

In [28]:
arr2.shape

(2, 4)

In [31]:
# np.array는 새로운 배열을 생성하기 위한 여러 함수를 갖고 있다. zeros 함수는 주어진 길이나 모양에 각각 0과 1이 들어 있는 배열을 생성.

np.zeros(5)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
np.zeros((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [35]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## 2. 인덱싱과 슬라이싱

In [84]:
data = np.array([1, 2, 3])

data[1]


2

In [85]:
data[0:2]

array([1, 2])

In [86]:
data[1:]

array([2, 3])

In [87]:
data[-2:]

array([2, 3])

In [70]:
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
arr[5] 

5

In [72]:
arr[5:8]

array([5, 6, 7])

In [73]:
arr[5:8] = 12 
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [74]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [75]:
arr_slice[2]= 5555
arr

array([   0,    1,    2,    3,    4,   12,   12, 5555,    8,    9])

In [76]:
# 다차원 배열 

arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr2d[2]

array([7, 8, 9])

In [77]:
arr2d[0][2]

3

In [91]:
# n차원 배열의 요소는 각 차원에서의 위치를 요소로 하는 튜플로 접근할 수 있다. 
# 예를 들어, (n, m) 크기의 ndarray X에서 i번째 행, j번째 열은 x[i, j]로 접근할 수 있다.
# 각 차원에서 인덱싱할 인덱스는 콤마로 구분한다.

import numpy as np 
X = [[1, 2], [3, 4]]
print(X[0][1])

X = np.array(X)
print(X[0, 1])  # 0번째 행, 1번째 열

2
2


## 3. 차원(Dimension)과 형태(Shape)

### 차원: 1, 2, 3차원, n차원
### 형태: 차원의 요소의 수 

#### 1차원 Shape (x, )  벡터 vector  [1차원 텐서]
#### 2차원 Shape (x, y), 행렬 matrix  [2차원 텐서]
#### 3차원 Shape (x, y, z), (면, 행, 열)  텐서 tensor [3차원 텐서]

....

####  n차원 Shape: (x, y, z....)

In [17]:
arr1 = np.array([1, 2, 3])    #1차원 
arr2 = np.array([[1, 2, 3], [4, 5, 6]])  # 2차원 
arr3 = np.array([[[1, 2], [3, 4]],[[5, 6], [7, 8]]])  #3차원

print(arr1.shape)  #크기가 3인 벡터 
print(arr2.shape)  #크기가 (2 x 3)인 행렬
print(arr3.shape)  # 크기가 (2 x 2 x 2)인 텐서

(3,)
(2, 3)
(2, 2, 2)


In [95]:
# 1차원 배열 
import numpy as np
data1 = [1, 2, 3, 4]  # 크기가 4인 벡터 
arr1 = np.array(data1)
arr1

array([1, 2, 3, 4])

In [94]:
#2차원 배열
data2 = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]   # (3*4) 행렬
arr2 = np.array(data2)
arr2        

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [102]:
# 3 차원 배열의 Shape : (면,행,열)
data3 = [[1, 2, 3, 4], [5, 6, 7, 8]],[[3, 4, 5, 6],[4, 5, 6, 7]]
arr3  = np.array(data3)
arr3

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[3, 4, 5, 6],
        [4, 5, 6, 7]]])

In [14]:
#차원(dimension) 확인
arr1.ndim

1

In [15]:
arr2.ndim

2

In [18]:
# 형태(shape) 확인
arr1.shape

(3,)

In [19]:
arr2.shape

(2, 3)

In [23]:
# 1 차원 배열의 Shape : (x,)
# np.arange(start,end+1,step)
a = np.arange(12)
print(a, type(a))
print(a.shape)    # (12,)
t = a.shape
print(type(t))    # <class 'tuple'>

a2 = np.arange(2,10)
print(a2,type(a2))
print(a2.shape)    # (8,)

a3 = np.arange(0,16,2)
print(a3,type(a3))
print(a3.shape)    # (8,)

[ 0  1  2  3  4  5  6  7  8  9 10 11] <class 'numpy.ndarray'>
(12,)
<class 'tuple'>
[2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
(8,)
[ 0  2  4  6  8 10 12 14] <class 'numpy.ndarray'>
(8,)


In [66]:
# 1차원 배열의 인덱싱과 슬라이싱 : list와 동일한 방법
d = np.arange(12)
print(d,d.shape)

print(d[0],d[1],d[2],d[-1],d[-2])
print(d[2:8],d[0:1],d[:],d[:-1])
print(d[::2],d[::-1])

d[0] = 10   # list 처럼 요소 변경이 가능
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)
0 1 2 11 10
[2 3 4 5 6 7] [0] [ 0  1  2  3  4  5  6  7  8  9 10 11] [ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10] [11 10  9  8  7  6  5  4  3  2  1  0]
[10  1  2  3  4  5  6  7  8  9 10 11]


In [24]:
# 2 차원 배열의 Shape : 행(row,가로,수직,axis=0) 과 열(column,세로,수평,axis=1) ==> 필수암기
# m = np.array([np.arange(3),np.arange(3)])
m = np.array([[0,1,2],
              [0,1,2]])
print(m)
print(m.shape)  # (2,3)
print(m.shape[0],m.shape[1])

[[0 1 2]
 [0 1 2]]
(2, 3)
2 3


In [67]:
# 2차원 배열의 인덱싱과 슬라이싱 
# data[행,열]
d = np.arange(12).reshape(3,4)
print(d,d.shape)

# 인덱싱
print(d[0][0]) # old style, 0
print(d[0,0])  # 0
print(d[2,1])  # 9

# 슬라이싱
print(d[0])    # [0 1 2 3]
print(d[0,:])  # [0 1 2 3]

print(d[:,:-1])   # (3,3), 마지막 열을 제외
print(d[::2,::2]) # (2,2)

d[0] = 20         # 0번 행의 모든 요소를 20으로 변경
print(d)
d[:,:] = -1       # 전체 요소를 한번에 변경할 수 있다
print(d)

d[::2,::3] = 30
print(d[::2,::3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)
0
0
9
[0 1 2 3]
[0 1 2 3]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]
[[ 0  2]
 [ 8 10]]
[[20 20 20 20]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]
[[30 30]
 [30 30]]


In [25]:
# 3 차원 배열의 Shape : (면,행,열)
m = np.array([[[0,1,2],
               [3,4,5]],
              [[0,1,2],
               [3,4,5]]])
print(m,m.ndim)  # 3차원
print(m.shape)   # (2,2,3)
print(m.shape[0],m.shape[1],m.shape[2])

m2 = np.array([[[0, 1],
                [2, 3]],
               [[4, 5],
                [0, 1]],
               [[2, 3],
                [4, 5]]])
print(m2,m2.ndim) # 3차원 
print(m2.shape)   # (3,2,2)

m3 = np.array([[[0, 1],
                [2, 3],
                [4, 5]],
               [[0, 1],
                [2, 3],
                [4, 5]]])
print(m2.shape) # (2,3,2)

[[[0 1 2]
  [3 4 5]]

 [[0 1 2]
  [3 4 5]]] 3
(2, 2, 3)
2 2 3
[[[0 1]
  [2 3]]

 [[4 5]
  [0 1]]

 [[2 3]
  [4 5]]] 3
(3, 2, 2)
(3, 2, 2)


In [68]:
# 3차원 배열의 인덱싱과 슬라이싱 
# data[면,행,열]
d = np.arange(12).reshape(2,2,3)
print(d,d.shape)

# 인덱싱
print(d[0][0][0])  # old style
print(d[0,0,0])    # 0
print(d[0,1,2])    # 5

# 슬라이싱
print(d[:,:-1,:-1]) # (2, 1, 2)
print('-'*30)
print(d[:,1:,1:])   # (2, 1, 2) , 3-D
print('-'*30)
print(d[:,:,-1])    # (2, 2) , matrix , 2차원으로 줄어든다
print('-'*30)
print(d[:,-1,-1])   # (2,), vector , 1차원으로 줄어든다
print(d[-1,-1,-1])  # scalar, 11

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]] (2, 2, 3)
0
0
5
[[[0 1]]

 [[6 7]]]
------------------------------
[[[ 4  5]]

 [[10 11]]]
------------------------------
[[ 2  5]
 [ 8 11]]
------------------------------
[ 5 11]
11


## 4. 배열의 연산: 유니버셜 함수와 브로드캐스팅 


#### 넘파이의 주요한 장점은 배열 간 매우 빠른 연산. 배열 간 연산이란 크기가 같은 두 배열에 대해 같은 위치에 있는 요소끼리 수행하는 연산을 의미
#### 유니버셜 함수: 파이썬에서 두 숫자형 변수에 대해 정의돈 연산자를 ndarray로 정의한 것. 즉, 유니버셜 함수는 벡터 및 행령 간 연산을 수행하는 연산 함수, 반복문보다 배열 간 연산을 훨신 빠르고 쉽게 구현할 수 있음
#### 브로드캐스팅: 크기가 서로 다른 배열 간 연산이 가능

In [48]:
A = np.arange(16).reshape(4,4)
print(A,A.shape)

print(A + 10)
print(A - 10)
print(A * 10)
print(A / 10)
print('-'*30)
print(10 + A)
print(10 - A)
print(10 * A)
print(10 / A)
print(10 / (A + 1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] (4, 4)
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
[[-10  -9  -8  -7]
 [ -6  -5  -4  -3]
 [ -2  -1   0   1]
 [  2   3   4   5]]
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]
 [120 130 140 150]]
[[0.  0.1 0.2 0.3]
 [0.4 0.5 0.6 0.7]
 [0.8 0.9 1.  1.1]
 [1.2 1.3 1.4 1.5]]
------------------------------
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
[[10  9  8  7]
 [ 6  5  4  3]
 [ 2  1  0 -1]
 [-2 -3 -4 -5]]
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]
 [120 130 140 150]]
[[        inf 10.          5.          3.33333333]
 [ 2.5         2.          1.66666667  1.42857143]
 [ 1.25        1.11111111  1.          0.90909091]
 [ 0.83333333  0.76923077  0.71428571  0.66666667]]
[[10.          5.          3.33333333  2.5       ]
 [ 2.          1.66666667  1.42857143  1.25      ]
 [ 1.11111111  1.          0.90909091  0.83333333]
 [ 0.76923077  0.71428571  0.66666667  0.625     ]]


C:\Users\hyeyo\AppData\Local\Temp/ipykernel_20692/2370739679.py:12: RuntimeWarning: divide by zero encountered in true_divide
  print(10 / A)


In [108]:
# 유니버셜 함수를 사용한 배열 산술 연산

x = np.arange(4)
y = np.linspace(1, 10, 4)
print("x   =", x)
print("y   =", y)
print("x + 2 =", x + 2)
print("x - 2 =", x - 2)
print("x + y =", x + y)
print("x * 2 =", x * 2)
print("x * y =", x * y)
print("x / y =", x / y)

x   = [0 1 2 3]
y   = [ 1.  4.  7. 10.]
x + 2 = [2 3 4 5]
x - 2 = [-2 -1  0  1]
x + y = [ 1.  5.  9. 13.]
x * 2 = [0 2 4 6]
x * y = [ 0.  4. 14. 30.]
x / y = [0.         0.25       0.28571429 0.3       ]


In [39]:
import numpy as np
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

arr


array([[1., 2., 3.],
       [4., 5., 6.]])

In [40]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [41]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
1/ arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [44]:
arr**3

array([[  1.,   8.,  27.],
       [ 64., 125., 216.]])

In [46]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [47]:
arr2 > arr   #불리언, 참/거짓 판단 

array([[False,  True, False],
       [ True, False,  True]])

### 브로드캐스팅 : 차원의 크기가 다른 배열 간의 산술연산

In [80]:
x = np.arange(4)
print(x+4)

[4 5 6 7]


In [81]:
# 크기가 서로 다른 (2, 2)인 a와 (2, 0) b 배열 간의 연산 (b가 a의 각 행에 더해짐)
## 브로드캐스팅에 의해 서로 다른 크기의 배열 간 연산이 가능

a = np.array([[1,2], [3,4]])
b = np.array ([-1, -2])
print(a + b)

[[0 0]
 [2 2]]


In [50]:
A = np.arange(6).reshape(3,2)
B = np.arange(2).reshape(1,2) + 1
print(A)
print(B)

print('-'*30)
print(A + B)
print(A - B) 
print(A * B)
print(A / B)
print('-'*30)
print(B + A)
print(B - A) 
print(B * A)
print(B / A)

[[0 1]
 [2 3]
 [4 5]]
[[1 2]]
------------------------------
[[1 3]
 [3 5]
 [5 7]]
[[-1 -1]
 [ 1  1]
 [ 3  3]]
[[ 0  2]
 [ 2  6]
 [ 4 10]]
[[0.  0.5]
 [2.  1.5]
 [4.  2.5]]
------------------------------
[[1 3]
 [3 5]
 [5 7]]
[[ 1  1]
 [-1 -1]
 [-3 -3]]
[[ 0  2]
 [ 2  6]
 [ 4 10]]
[[       inf 2.        ]
 [0.5        0.66666667]
 [0.25       0.4       ]]


C:\Users\hyeyo\AppData\Local\Temp/ipykernel_20692/261408139.py:15: RuntimeWarning: divide by zero encountered in true_divide
  print(B / A)
